export const DOCTORS = [
  {
    id: "1",
    name: "Dr. Prakash Das",
    specialty: "Sr. Psychologist",
    qualification: "MBBS, MD (Psychiatry)",
    hospital: "Apollo Hospital, Mumbai",
    patients: 5000,
    experience: 7,
    rating: 4.8,
    reviews: 4942,
    hours: "09:30 AM – 07:00 PM",
    service: "OPD / Online",
    specialization: "Psychology",
    about: "7+ years in mental health, cognitive behavioral therapy, and stress management providing compassionate care for anxiety and depression.",
    availability: "Available today",
    isFavorite: false,
  },
  {
    id: "2",
    name: "Dr. Kumar Das",
    specialty: "Ophthalmologist",
    qualification: "MBBS, MS (Surgeon)",
    hospital: "Sanskara Netralaya, Chennai",
    patients: 5000,
    experience: 10,
    rating: 4.9,
    reviews: 4942,
    hours: "10:00 AM – 05:00 PM",
    service: "OPD",
    specialization: "Ophthalmology",
    about: "15+ years in ophthalmology specializing in cataract surgery, LASIK, glaucoma management and complex retinal procedures.",
    availability: "Available today",
    isFavorite: false,
  },
  {
    id: "3",
    name: "Dr. Priya Sharma",
    specialty: "Cardiologist",
    qualification: "MBBS, DM (Cardiology)",
    hospital: "Fortis Hospital, Delhi",
    patients: 8000,
    experience: 12,
    rating: 4.9,
    reviews: 6120,
    hours: "09:00 AM – 06:00 PM",
    service: "OPD / Emergency",
    specialization: "Cardiology",
    about: "12+ years in interventional cardiology. Performed 3000+ successful cardiac procedures with expertise in preventive cardiology.",
    availability: "Available today",
    isFavorite: true,
  },
  {
    id: "4",
    name: "Dr. Rahul Mehta",
    specialty: "Dermatologist",
    qualification: "MBBS, MD (Dermatology)",
    hospital: "Skin & Care Clinic, Pune",
    patients: 4200,
    experience: 8,
    rating: 4.7,
    reviews: 3100,
    hours: "10:00 AM – 07:00 PM",
    service: "OPD",
    specialization: "Dermatology",
    about: "Certified dermatologist specializing in cosmetic dermatology, acne treatment, and skin cancer detection with latest laser tech.",
    availability: "Next available",
    isFavorite: false,
  },
  {
    id: "5",
    name: "Dr. Sneha Joshi",
    specialty: "Pediatrician",
    qualification: "MBBS, MD (Pediatrics)",
    hospital: "Rainbow Children Hospital, Hyderabad",
    patients: 9500,
    experience: 15,
    rating: 4.9,
    reviews: 7800,
    hours: "08:30 AM – 05:30 PM",
    service: "OPD / Online",
    specialization: "Pediatrics",
    about: "15 years in pediatric healthcare specializing in neonatal care, childhood immunizations, and developmental pediatrics.",
    availability: "Available today",
    isFavorite: false,
  },
  {
    id: "6",
    name: "Dr. Arun Patel",
    specialty: "Orthopedic Surgeon",
    qualification: "MBBS, MS (Orthopedics)",
    hospital: "Bone & Joint Center, Ahmedabad",
    patients: 6300,
    experience: 11,
    rating: 4.6,
    reviews: 4200,
    hours: "09:00 AM – 04:00 PM",
    service: "OPD / Surgery",
    specialization: "Orthopedics",
    about: "Leading orthopedic surgeon with expertise in joint replacement, sports injuries, and spine surgery. 5000+ successful procedures.",
    availability: "Available today",
    isFavorite: false,
  },
  {
  id: "7",
  name: "Dr. Neha Kapoor",
  specialty: "Gynecologist",
  qualification: "MBBS, MD (Obstetrics & Gynecology)",
  hospital: "Cloudnine Hospital, Bengaluru",
  patients: 7200,
  experience: 9,
  rating: 4.8,
  reviews: 5100,
  hours: "09:00 AM – 04:00 PM",
  service: "OPD / Online",
  specialization: "Gynecology",
  about: "Specialist in high-risk pregnancies, infertility treatment, and minimally invasive gynecological procedures with 9+ years experience.",
  availability: "Available today",
  isFavorite: false,
},
{
  id: "8",
  name: "Dr. Amit Verma",
  specialty: "Neurologist",
  qualification: "MBBS, DM (Neurology)",
  hospital: "Max Super Speciality Hospital, Delhi",
  patients: 8400,
  experience: 14,
  rating: 4.9,
  reviews: 6900,
  hours: "10:00 AM – 06:00 PM",
  service: "OPD / Emergency",
  specialization: "Neurology",
  about: "14 years experience in stroke management, epilepsy treatment, and neurodegenerative disorders with advanced neuro-diagnostics.",
  availability: "Next available",
  isFavorite: false,
},
{
  id: "9",
  name: "Dr. Kavita Iyer",
  specialty: "Endocrinologist",
  qualification: "MBBS, MD (Medicine), DM (Endocrinology)",
  hospital: "Manipal Hospital, Bengaluru",
  patients: 6100,
  experience: 11,
  rating: 4.7,
  reviews: 4300,
  hours: "08:30 AM – 03:30 PM",
  service: "OPD",
  specialization: "Endocrinology",
  about: "Expert in diabetes management, thyroid disorders, PCOS, and hormonal imbalance treatment with evidence-based care.",
  availability: "Available today",
  isFavorite: false,
},
{
  id: "10",
  name: "Dr. Sanjay Rao",
  specialty: "General Physician",
  qualification: "MBBS, MD (Internal Medicine)",
  hospital: "Kokilaben Hospital, Mumbai",
  patients: 12000,
  experience: 16,
  rating: 4.8,
  reviews: 8800,
  hours: "09:00 AM – 08:00 PM",
  service: "OPD / Online",
  specialization: "General Medicine",
  about: "Senior physician with 16+ years of experience managing chronic illnesses, lifestyle diseases, and preventive healthcare.",
  availability: "Available today",
  isFavorite: false,
},
{
  id: "11",
  name: "Dr. Ritu Malhotra",
  specialty: "ENT Specialist",
  qualification: "MBBS, MS (ENT)",
  hospital: "AIIMS, New Delhi",
  patients: 5300,
  experience: 8,
  rating: 4.6,
  reviews: 3200,
  hours: "10:30 AM – 05:30 PM",
  service: "OPD / Surgery",
  specialization: "ENT",
  about: "Experienced ENT surgeon specializing in sinus surgery, hearing disorders, and pediatric ENT conditions.",
  availability: "Next available",
  isFavorite: false,
},
{
  id: "12",
  name: "Dr. Aditya Kulkarni",
  specialty: "Oncologist",
  qualification: "MBBS, MD (Oncology)",
  hospital: "Tata Memorial Hospital, Mumbai",
  patients: 4700,
  experience: 13,
  rating: 4.9,
  reviews: 5600,
  hours: "09:30 AM – 04:30 PM",
  service: "OPD / Chemotherapy",
  specialization: "Oncology",
  about: "Medical oncologist with 13+ years of experience in breast, lung, and gastrointestinal cancers providing comprehensive cancer care.",
  availability: "Available today",
  isFavorite: false,
},
];

export const SPECIALTIES = [
  "All",
  "Psychology",
  "Cardiology",
  "Ophthalmology",
  "Dermatology",
  "Pediatrics",
  "Orthopedics",
  "Gynecology",
  "Neurology",
  "Endocrinology",
  "General Medicine",
  "ENT",
  "Oncology",
];
export const AVATAR_COLORS = [
  { bg: "#dbeafe", text: "#1d4ed8", light: "#eff6ff" },
  { bg: "#dcfce7", text: "#15803d", light: "#f0fdf4" },
  { bg: "#f3e8ff", text: "#7c3aed", light: "#faf5ff" },
  { bg: "#fce7f3", text: "#be185d", light: "#fdf2f8" },
  { bg: "#fef3c7", text: "#b45309", light: "#fffbeb" },
  { bg: "#ffedd5", text: "#c2410c", light: "#fff7ed" },
];

export const PATIENTS = [
  {
    id: "p1",
    name: "Priya Sharma",
    age: 28,
    gender: "Female",
    phone: "+91 9876543210",
    email: "priya@example.com",
    location: "Dombivali, Mumbai",
    bloodGroup: "B+",
    weight: "58 kg",
    height: "162 cm",
    lastVisit: "Feb 20, 2025",
    nextVisit: "Mar 6, 2025",
    status: "Active",
    conditions: ["Myopia", "Mild Astigmatism"],
    allergies: ["Penicillin", "Dust"],
    medications: [
      { name: "Lubricating Eye Drops", dose: "2 drops", frequency: "3x daily" },
      { name: "Vitamin A Supplement", dose: "10,000 IU", frequency: "Once daily" },
    ],
    vitals: [
      { bp: "118/76", pulse: "72 bpm", temp: "98.4°F", oxygen: "99%", date: "Feb 20" },
      { bp: "120/78", pulse: "74 bpm", temp: "98.6°F", oxygen: "98%", date: "Jan 15" },
    ],
    visits: [
      { date: "Feb 20, 2025", reason: "Routine eye check", notes: "Power stable at -2.5D both eyes. No progression. Recommended yearly review.", prescription: "Continue current glasses, no change." },
      { date: "Jan 15, 2025", reason: "Eye irritation", notes: "Mild dryness due to screen time. Prescribed lubricating drops.", prescription: "Systane Ultra 4x daily for 2 weeks." },
    ],
    avatar: { bg: "#fce7f3", text: "#be185d" },
  },
  {
    id: "p2",
    name: "Rohan Mehta",
    age: 45,
    gender: "Male",
    phone: "+91 9845230011",
    email: "rohan.mehta@gmail.com",
    location: "Andheri, Mumbai",
    bloodGroup: "O+",
    weight: "78 kg",
    height: "175 cm",
    lastVisit: "Feb 18, 2025",
    nextVisit: "Feb 25, 2025",
    status: "Follow-up",
    conditions: ["Glaucoma (Early Stage)", "Hypertension"],
    allergies: ["Sulfa drugs"],
    medications: [
      { name: "Timolol Eye Drops", dose: "1 drop", frequency: "2x daily" },
      { name: "Amlodipine", dose: "5mg", frequency: "Once daily" },
    ],
    vitals: [
      { bp: "142/90", pulse: "82 bpm", temp: "98.6°F", oxygen: "97%", date: "Feb 18" },
      { bp: "148/94", pulse: "86 bpm", temp: "98.8°F", oxygen: "97%", date: "Jan 22" },
    ],
    visits: [
      { date: "Feb 18, 2025", reason: "Glaucoma follow-up", notes: "IOP reduced from 26 to 21 mmHg with medication. Peripheral vision stable.", prescription: "Timolol 0.5% — continue, review in 3 weeks." },
      { date: "Jan 22, 2025", reason: "Blurred vision", notes: "Diagnosed early-stage glaucoma. Started on Timolol drops.", prescription: "Timolol 0.5% BID, visual field test scheduled." },
    ],
    avatar: { bg: "#dbeafe", text: "#1d4ed8" },
  },
  {
    id: "p3",
    name: "Ananya Krishnan",
    age: 34,
    gender: "Female",
    phone: "+91 9712345678",
    email: "ananya.k@outlook.com",
    location: "Powai, Mumbai",
    bloodGroup: "A-",
    weight: "62 kg",
    height: "158 cm",
    lastVisit: "Feb 15, 2025",
    status: "Recovered",
    conditions: ["Cataract (Post-op)"],
    allergies: ["None known"],
    medications: [
      { name: "Prednisolone Eye Drops", dose: "1 drop", frequency: "Tapering dose" },
    ],
    vitals: [
      { bp: "116/74", pulse: "68 bpm", temp: "98.4°F", oxygen: "99%", date: "Feb 15" },
    ],
    visits: [
      { date: "Feb 15, 2025", reason: "Post-op cataract review (Week 2)", notes: "Excellent recovery. Vision 6/6 in right eye. No inflammation.", prescription: "Taper Prednisolone: 3x daily week 3, 2x daily week 4, stop." },
    ],
    avatar: { bg: "#dcfce7", text: "#15803d" },
  },
  {
    id: "p4",
    name: "Vikram Nair",
    age: 62,
    gender: "Male",
    phone: "+91 9900112233",
    email: "vikram.nair@yahoo.com",
    location: "Thane, Mumbai",
    bloodGroup: "AB+",
    weight: "85 kg",
    height: "170 cm",
    lastVisit: "Feb 22, 2025",
    nextVisit: "Mar 1, 2025",
    status: "Critical",
    conditions: ["Diabetic Retinopathy (Stage 3)", "Type 2 Diabetes", "Hypertension"],
    allergies: ["Aspirin", "Latex"],
    medications: [
      { name: "Metformin", dose: "500mg", frequency: "2x daily" },
      { name: "Ranibizumab Injection", dose: "0.5mg", frequency: "Monthly intravitreal" },
    ],
    vitals: [
      { bp: "156/98", pulse: "88 bpm", temp: "99.1°F", oxygen: "96%", date: "Feb 22" },
    ],
    visits: [
      { date: "Feb 22, 2025", reason: "Retinopathy management", notes: "New microaneurysms noted. 3rd Anti-VEGF injection administered.", prescription: "Ranibizumab injection administered. HbA1c target <7%." },
    ],
    avatar: { bg: "#fef3c7", text: "#b45309" },
  },
  {
    id: "p5",
    name: "Shalini Bose",
    age: 22,
    gender: "Female",
    phone: "+91 9654321098",
    email: "shalini.bose@gmail.com",
    location: "Navi Mumbai",
    bloodGroup: "O-",
    weight: "52 kg",
    height: "155 cm",
    lastVisit: "Feb 10, 2025",
    status: "Active",
    conditions: ["Keratoconus (Mild)", "Dry Eye Syndrome"],
    allergies: ["Cat dander"],
    medications: [
      { name: "Carboxymethylcellulose Drops", dose: "1 drop", frequency: "5x daily" },
    ],
    vitals: [
      { bp: "110/70", pulse: "66 bpm", temp: "98.2°F", oxygen: "99%", date: "Feb 10" },
    ],
    visits: [
      { date: "Feb 10, 2025", reason: "Keratoconus screening follow-up", notes: "Corneal topography shows mild progression. Considering Cross-Linking.", prescription: "Intense lubrication. Rigid contact lens trial scheduled." },
    ],
    avatar: { bg: "#f3e8ff", text: "#7c3aed" },
  },
  {
    id: "p6",
    name: "Arjun Patel",
    age: 38,
    gender: "Male",
    phone: "+91 9988776655",
    email: "arjun.patel@company.com",
    location: "Bandra, Mumbai",
    bloodGroup: "B-",
    weight: "72 kg",
    height: "178 cm",
    lastVisit: "Jan 28, 2025",
    nextVisit: "Apr 28, 2025",
    status: "Recovered",
    conditions: ["LASIK (Post-op)", "Mild Dry Eye"],
    allergies: ["None known"],
    medications: [
      { name: "Lubricating Eye Drops", dose: "1 drop", frequency: "As needed" },
    ],
    vitals: [
      { bp: "122/80", pulse: "70 bpm", temp: "98.6°F", oxygen: "99%", date: "Jan 28" },
    ],
    visits: [
      { date: "Jan 28, 2025", reason: "LASIK 3-month post-op review", notes: "Outstanding outcome. Vision 6/5 both eyes. Patient very satisfied.", prescription: "PRN lubricants only. Next review at 6 months." },
    ],
    avatar: { bg: "#ffedd5", text: "#c2410c" },
  },
];
